### ISSUE TITLE
Add HEX color support in tastykitchen[ui]

### ISSUE THREAD

**Issue by JulianGiles** [ahuang11/tastymap#15]
It would be nice to have the option to add HEX color code when manually adding colors in the UI.

I mean here, you can see HEX code when importing a colormap but I am not able to add new colors in HEX format
![Screenshot_20231214_090100](https://github.com/ahuang11/tastymap/assets/87534521/e21bde47-1f87-4523-8198-01af42c735fd)

**Comment by ahuang11** [comment]
Huh strange; I thought I supported it~

Would you be interested in contributing a PR? If so, I think adding a check for `color.startswith("#")` here would do it:
https://github.com/ahuang11/tastymap/blob/main/tastymap/ui.py#L418-L447

**Comment by JulianGiles** [comment]
thanks!
